// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.info("Adil");

console.warn("Adil");

console.error("Adil");

console.count();

console.count();

console.count();

console.count();

console.count();

/*  Not a pure module */
