// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log("LOG");

console.warn("WARNING");

console.info("INFO");

console.error("ERROR");

var timeId = setTimeout((function (param) {
        console.clear();
        
      }), 2000);

clearTimeout(timeId);

exports.timeId = timeId;
/*  Not a pure module */
